[technote]
id = "RTN-104"
series_id = "RTN"
canonical_url = "https://rtn-104.lsst.io"
github_url = "https://github.com/lsst/rtn-104"
github_default_branch = "main"
date_created = 2025-07-01T21:00:55Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Antonia Sierra"
name.family = "Villarreal"
internal_id = "villarreala"
orcid = "https://orcid.org/0000-0002-8847-0335"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
